# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import segmentation_pb2 as segmentation__pb2


class DetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detect = channel.unary_unary(
                '/segmentation.Detection/detect',
                request_serializer=segmentation__pb2.DetectionRequest.SerializeToString,
                response_deserializer=segmentation__pb2.DetectionResult.FromString,
                )


class DetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detect': grpc.unary_unary_rpc_method_handler(
                    servicer.detect,
                    request_deserializer=segmentation__pb2.DetectionRequest.FromString,
                    response_serializer=segmentation__pb2.DetectionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'segmentation.Detection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Detection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/segmentation.Detection/detect',
            segmentation__pb2.DetectionRequest.SerializeToString,
            segmentation__pb2.DetectionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SegmentationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.segment = channel.unary_unary(
                '/segmentation.Segmentation/segment',
                request_serializer=segmentation__pb2.SegmentationRequest.SerializeToString,
                response_deserializer=segmentation__pb2.SegmentationResult.FromString,
                )


class SegmentationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def segment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'segment': grpc.unary_unary_rpc_method_handler(
                    servicer.segment,
                    request_deserializer=segmentation__pb2.SegmentationRequest.FromString,
                    response_serializer=segmentation__pb2.SegmentationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'segmentation.Segmentation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Segmentation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def segment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/segmentation.Segmentation/segment',
            segmentation__pb2.SegmentationRequest.SerializeToString,
            segmentation__pb2.SegmentationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
